### ISSUE TITLE
CoM task

### ISSUE THREAD

**Issue by ddliu365** [stephane-caron/pink#57]
Hi, Stéphane, I am wondering if there is a CoM task for a humanoid robot in current framework.

Need to use pink to solve IK using a LIPM model.

**Comment by stephane-caron** [comment]
There is CoM task yet, but as pointed out in [`CONTRIBUTING.md`](https://github.com/tasts-robots/pink/blob/33bc81c83f9becc96d4ed5407e7ab0e6faff8f03/CONTRIBUTING.md) there is an existing reference for it in Pymanoid. Porting it to Pink would be totally welcome, if you want to take a stab at this I can help with reviewing the PR :smiley:

**Comment by simeon-ned** [comment]
@ddliu365, a friendly reminder that the CoM task was introduced in the last PR #96. @stephane-caron I believe we can close this issue for now. :)
