### ISSUE TITLE
Attribute Error : 'FrameTask' object has no attribute 'frame' 

### ISSUE THREAD

**Issue by PranayG** [stephane-caron/pink#77]
When you run the arm_ur5.py example it gives an error:

`
Attribute Error : 'FrameTask' object has no attribute 'frame' 
`

end_effector_task.frame is not defined

The class Frame Task has no attribute frame in the examples/arm_ur5.py

The same error is persistent with other arm_ur3.py and other examples

**Comment by stephane-caron** [comment]
Thank you for reporting this :+1: We were overdue a release, which is now out with version 2.0.0. Can you try updating to the latest version and test the example again?

Feel free to re-open this issue if there is still an error in the examples.

**Comment by PranayG** [comment]
Thanks. It works now.
