### ISSUE TITLE
Proposal for Integration of Control Barrier Functions (CBFs) into pink

### ISSUE THREAD

**Issue by domrachev03** [stephane-caron/pink#86]
Hello Dr. Caron,

First of all, thank you for maintaining the **pink** repository. I found it extremely useful in practice.

My colleague [@simeon-ned](https://github.com/simeon-ned) and I have been actively working on the concept of **Control Barrier Functions (CBFs)** in robotic applications. This approach integrates seamlessly into QP-like formulations and it was intriguing for us to incorporate it into **pink** to ensure safety limitations, specifically solving IK with inequality constraints:

$$h(q) \geq 0$$

We have added this functionality in **pink**. You can find our forked repository here: [link](https://github.com/domrachev03/pink/). The notes on the related theory can be found [in the example notebook](https://github.com/domrachev03/pink/blob/main/examples/barriers/barrier.ipynb).

So far, we have added a new `Barriers` abstract class, along with several practical barriers:
- **PositionBarrier**: [PositionBarrier implementation](https://github.com/domrachev03/pink/blob/main/pink/barriers/position_barrier.py)
- **ConfigurationBarrier**: [ConfigurationBarrier implementation](https://github.com/domrachev03/pink/blob/main/pink/barriers/configuration_barrier.py) (can be seen as an alternative to limits)
- **Body Spherical Barrier**: [Body Spherical Barrier implementation](https://github.com/domrachev03/pink/blob/main/pink/barriers/body_spherical_barrier.py) (for self-collision avoidance)

Documentation for these features, based on our fork, can be found on our local copy of GitHub pages: [Barriers Documentation](https://domrachev03.github.io/pink/barriers.html).

To demonstrate the capabilities of these features, we have developed two examples:

1. **Joint and End Effector Barriers in UR5 Robot**:
   - [UR5 Robot Example Code](https://github.com/domrachev03/pink/blob/main/examples/barriers/arm_ur5.py)
   

https://github.com/stephane-caron/pink/assets/28687492/06e903cc-ab7f-4fd4-a09f-adae3b26e211

2. **Spherical Self Collisions in Two Arms Yumi Robot**:
   - [Yumi Robot Example Code](https://github.com/domrachev03/pink/blob/main/examples/barriers/arms_yumi.py)
   

https://github.com/stephane-caron/pink/assets/28687492/ba30854b-8cac-4b18-80e9-503d4273015d

We are eager to contribute these enhancements to your repository, believing they will greatly benefit the community. We are prepared to develop comprehensive tests and consider the integration of more complex geometries for self-collision management using the HPP FCL library, pending your approval.

We look forward to your feedback and hope for a positive collaboration.

Best regards,

Ivan Domrachev

**Comment by luoleicn** [comment]
@domrachev03 hi, thanks to your greate work, I tried it but I found  it dont work for floating base robot, because Hessian matrix from Task is based on velocity vector space, and  Hessian matrix from Barrier is based on configuration vector space, they dont match for floating base robot

**Comment by domrachev03** [comment]
Hello, @luoleicn, thank you for your interest in our solution!

It can be the case, because there is no test for floating base model in our fork. Could you provide your code so that we could debug it and fix dimension issues?

**Comment by jcarpent** [comment]
A small hint for extending your code to more complex configuration space is to use `pin.difference(model,q0,q1)` to properly measure the difference between two configuration vectors defined on Lie groups, as the one occurring for floating-base systems.

**Comment by simeon-ned** [comment]
@jcarpent Totally! Thanks for reminding us about the magic of tangent space – can't believe we overlooked it, will fix it soon. Also, huge thanks for Pinocchio, I'm using it every day and it's awesome!

**Comment by simeon-ned** [comment]
@jcarpent Certainly it is! Looking forward to v3 :). 

I just went through our code, turns out we used the correct difference to subtract the two configurations in the configuration barrier, however it may be the case that we forgot to use it somewhere. For now, the problem is that we just used joint dim nq instead of nv in hessians and gradients as @luoleicn mentioned. I'll fix this today or tomorrow and post an example with some robot with floating joints, like Unitree Go2.

**Comment by stephane-caron** [comment]
This looks great @domrachev03 @simeon-ned :star_struck: It would be a significant improvement for Pink, and I'd be happy to help review and integrate it.

If you can split it into successive functional PRs (for instance starting with the positional barrier, adding unit tests, then adding the other barriers one by one), it will probably make it smoother for us to review and merge them progressively.

Feel free to open a PR when you are ready :+1:

**Comment by simeon-ned** [comment]
Thank you @stephane-caron for the positive feedback! We're really glad to contribute and are excited to see this improvement for Pink. We'll definitely split the work into successive functional PRs as you suggested, starting with the positional barrier and its unit tests. You can expect the first PR to be opened this week. Looking forward to collaborating on this! 👍

**Comment by simeon-ned** [comment]
@luoleicn we fixed the floating base issue and added an example of go2 robot performing squats with constraints $y\leq0, z\leq0.35$, thanks for pointing out this bug. 

https://github.com/stephane-caron/pink/assets/26837717/2bf999b7-4ffe-4f67-a513-3d9828ef2d45

**Comment by domrachev03** [comment]
I think for now the is enough, so I suggest we close this issue till new ideas for CBF would arise!

**Comment by stephane-caron** [comment]
Thank you both for following through all the way with your proposal :muscle: Barriers are a significant feature improvement to the library. Let's move onward to releasing Pink v3 so that more users can access it :smiley:
