### ISSUE TITLE
Velocity vibrations in Go2 position barrier example

### ISSUE THREAD

**Issue by dbdxnuliba** [stephane-caron/pink#98]
![aaa](https://github.com/stephane-caron/pink/assets/13350158/aa14cbf2-cd6a-40ed-973f-d6a8edb26908)

buy test the demo "python3 examples/barriers/go2_squat.py"
  speed  vibration occurs,how can we solve the problem ,thanks

**Comment by simeon-ned** [comment]
@dbdxnuliba As the one who implemented this example, I will try to help. The issues here may be near the boundary of the barrier, or in tuning tasks in general. To avoid this, you might try adjusting `safe_displacement_gain` in the [barrier](https://stephane-caron.github.io/pink/barriers.html) constructor and `lm_damping` in [`solve_ik`](https://stephane-caron.github.io/pink/inverse-kinematics.html). However, it is hard to see the vibrations; it seems more like a problem with visualization. I will add a video of how this example is executed on my machine. I suggest studying the plots for the velocity coming out from `solve_ik` first.

https://github.com/stephane-caron/pink/assets/26837717/4cc17ef4-a895-4aa3-b37f-e67de9dde5f6

**Comment by dbdxnuliba** [comment]
ok thanks
